name: kaggle
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - requests
  - ipykernel
  - pip
  - pip:
      - python-dotenv
      - habanero
      - serpapi
      - google-search-results
      - openpyxl
      - Jinja2
      - kagglehub